name: 'one and two'

on: push

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-one
      - uses: ./.github/actions/test-two
